### ISSUE TITLE
Normalize `abs`

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#268]
https://godbolt.org/g/SskGN9

On other platforms, `std::abs(int)` returns `double`!! Clean this up so `cnl::abs` does sane and consistent things on all platforms. For bonus points, make it conform to `std::abs`.

**Comment by johnmcfarlane** [comment]
Also, `constexpr`.

**Comment by johnmcfarlane** [comment]
Also, `constexpr`.

**Comment by keryell** [comment]
I discovered recently that `std::abs` was not `constexpr` so I need to reimplement it to be used in metaprogramming... :-(

**Comment by johnmcfarlane** [comment]
Generic Numerics!

**Comment by johnmcfarlane** [comment]
Fixed in #270

**Comment by johnmcfarlane** [comment]
Example started not failing so here's [an alternative](https://godbolt.org/z/3CrOOU) which breaks correctly.

**Comment by johnmcfarlane** [comment]
(https://bugs.llvm.org/show_bug.cgi?id=36479)?
