### ISSUE TITLE
VS2017 v15.8.1 Compilation Error

### ISSUE THREAD

**Issue by colin-branch** [johnmcfarlane/cnl#269]
Compile error occurs with any trivial source file which includes cnl headers including benchmark.cpp

1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(71): error C2953: 'cnl::_impl::set_digits_signed<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(76): error C2953: 'cnl::_impl::set_digits_signed<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(81): error C2953: 'cnl::_impl::set_digits_signed<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(93): error C2953: 'cnl::_impl::set_digits_signed<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(109): error C2953: 'cnl::_impl::set_digits_unsigned<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(114): error C2953: 'cnl::_impl::set_digits_unsigned<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(119): error C2953: 'cnl::_impl::set_digits_unsigned<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined
1>C:\cnl-develop\include\cnl\_impl\num_traits\set_digits.h(131): error C2953: 'cnl::_impl::set_digits_unsigned<MinNumDigits,std::enable_if<'function'&&'function',void>::type>': class template has already been defined

**Comment by johnmcfarlane** [comment]
Thank you for reporting this. I currently only test on AppVeyor [which uses 15.7.180.61344](https://ci.appveyor.com/project/johnmcfarlane/cnl/build/0.1.1147/job/1fq5rg3bb6tf0o2o) and my Windows PC is sent off for repairs after the batter failed. So I might not be able to reproduce this for a while.

**Comment by druerridge** [comment]
Seeing this also, it seems to have happened as we went from Visual Studio 2017 15.7.XXX -> 15.8.XXX, at least on the two machines we've been running on.

Just happened to me today when I updated to latest VS version 15.8.05077.0.

**Comment by johnmcfarlane** [comment]
The same errors were appearing in CI builds a few days ago. #276 addressed those. Could you confirm whether or not the problem persists at head?

**Comment by druerridge** [comment]
That fixed it, thanks!  I should have just tried that, haha.

**Comment by johnmcfarlane** [comment]
Great. Closing. :)
