### ISSUE TITLE
Rounding free function failure

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#283]
static constexpr auto a = cnl::elastic_number<8, -4>{0.3125};
    static constexpr auto b = cnl::convert<cnl::nearest_rounding_tag, cnl::elastic_number<4, -1>>{}(a);
    static_assert(identical(cnl::elastic_number<4, -1>{0.5}, b),"Free rounding test1"); //Works

    static constexpr auto c = cnl::convert<cnl::nearest_rounding_tag, cnl::elastic_number<4, -2>>{}(a);
    static_assert(identical(cnl::elastic_number<4, -2>{0.25}, c),"Free rounding test2"); //Fails gives 0.75 as result.

**Comment by johnmcfarlane** [comment]
@hbe72 could you try it now? Thanks

**Comment by hbe72** [comment]
Tried, and seems to work.

However, I'm a bit puzzled why I can write
```cpp
    static constexpr auto a = cnl::elastic_number<8, -4>{0.3125};
    static constexpr auto b = cnl::_impl::convert<cnl::nearest_rounding_tag, cnl::elastic_number<4, -1>>(a); // Computes
    static constexpr auto c = cnl::convert<cnl::nearest_rounding_tag, cnl::elastic_number<4, -1>, cnl::elastic_number<8, -4>>{}(a); //Compiles
    static constexpr auto d = cnl::convert<cnl::nearest_rounding_tag, cnl::elastic_number<4, -1>>{}(a); //Missing template parameter

```
The template specification for cnl::_impl::convert is a function, cnl::convert is a "functor". Can we get rid of the third template parameter or lift the _impl namespace from the function?

**Comment by hbe72** [comment]
Would you consider adding following to cnl/_imp/rounding/convert.h ?
```cpp
    template<typename Result, typename Input>
    struct convert<
             _impl::nearest_rounding_tag, Result, Input,
             _impl::enable_if_t<
                    std::is_floating_point<Result>::value && std::is_floating_point<Input>::value>> {
        constexpr Result operator()(Input const& from) const
        {
            return static_cast<Result>(from);
        }
```

Thus nearest rounding for a floating point - floating point conversion does just static cast from type to another. I can foresee that type agnostic code could have type conversions with rounding  with fixed_point types and no rounding with floating point types.

Of course it is true that we could round (or truncate) coming from double to float, but do we want to do things differently compared to current C++ with native datatypes?

**Comment by johnmcfarlane** [comment]
In answer to your previous question about `cnl::convert` vs `cnl::_impl::convert`, `convert` is primarily a customization point. The `_impl` function is an internal helper which you're welcome to reimplement until I figure out customization. It's an open area right now. I'd like to ape what [range-v3](https://github.com/ericniebler/range-v3) does as @ericniebler has put a lot of thought into this topic. (There is also some interest from the embedded world in being able to customize much of CNL for exotic numeric types.) But I haven't gotten around to this task as `multiword_integer` is a more pressing issue. (People are always running out of bits as I'm sure you're aware!)

**Comment by johnmcfarlane** [comment]
Also on the TODO list: `convert<whatever_rounding_tag>` with `rounding_integer<>` input and result.

**Comment by hbe72** [comment]
I started testing what you proposed earlier

```cpp
    static constexpr auto a = cnl::fixed_point<int, -4>{0.3125};
    using native_rounding_type = typename cnl::_impl::set_rounding<cnl::fixed_point<int, -1>, cnl::_impl::native_rounding_tag>::type;
    static constexpr auto b = static_cast<native_rounding_type>(a);
    static_assert(identical(static_cast<native_rounding_type>(0.5f), b),
              "cnl::convert<nearest_rounding_tag, fixed_point, fixed_point>");
```

Should this work, or did I find a bug?
The value of b is 0 after the static_cast and the static_assert fails.
