### ISSUE TITLE
Make `elastic_integer` an alias

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#284]
The `NumDigits` in `cnl::elastic_integer<NumDigits, Integer>` may have been a mistake. Repurpose it as `promote_integer<Integer>` so that, e.g. operator+ doubles the width of the result.

New layout:

    template<typename Rep>
    promote_integer;

    template<int Digits, typename Narrowest>
    wide_integer;

    template<int Digits, typename Narrowest>
    using elastic_integer = promote_integer<wide_integer<Digits, Narrowest>>;

**Comment by elcojacobs** [comment]
I'm not sure I fully understand what you mean here, but it would be very useful for me if I can define a fixed_point<24,0, int32_t>, which does not saturate its underlying type.
When two of these are multiplied, I need a promoted type, but for addition, the type already has enough room to grow.

The elastic integer seems to provide exactly that: promoting to a bigger type only when it is needed. For addition, it only needs one extra integer bit and if and if there are unused digits left, no underlying type promotion is needed.

**Comment by johnmcfarlane** [comment]
The alias version of `elastic_integer` would do this. Because `cnl::digits` and `cnl::set_digits` would be used by `promote_integer` to decide the appropriate width of return types, and because `wide_integer` is bit-resolution, you'd get the same extra single bit when adding and double the bits when multiplying. 

You can get your fixed-point type currently using `fixed_point<elastic_integer<24>>`. When they are added, you get `fixed_point<elastic_integer<24>>`. That wouldn't change if `elastic_integer` became an alias but `wide_integer` would now take on the job of keeping track of the exact number of bits.

**Comment by johnmcfarlane** [comment]
This appears to be captured/superseded by #864.
