### ISSUE TITLE
How to access the raw underlying type for a composite type?

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#287]
Hi John,

I just started refactoring my code to use your library. It looks fantastic!
I've been struggling with what should probably be very simple for a couple of hours now. I see you are in the process of refactoring `to_rep` and `from_rep` and committed some changes a couple of hours ago.
Could you help me understand their usage?

I have this type
```
template <
    int IntegerDigits,
    int FractionalDigits,
    class Narrowest>
using safe_elastic_fixed_point = cnl::fixed_point<
    cnl::overflow_integer<
        cnl::elastic_integer<
            IntegerDigits + FractionalDigits,
            Narrowest>,
        cnl::saturated_overflow_tag>,
    -FractionalDigits>;

using temp_t = safe_elastic_fixed_point<7, 8, int16_t>;
```
It provides me with all the awesome math without losing precision if I use auto for the intermediate results and saturation when assigning to a narrow type. Exactly what I wanted.

But yo send my data over the wire using protobuf, I just want to send/receive the raw `int16_t`, the underlying type `Narrowest`.

What would be the best way to do that?

Would it be possible to provide: 
```
// a static function for construction from rep
static temp_t temp_t::from_rep(const int16_t & rep);

// a member function for accessing as rep
int16_t temp_t temp_t::to_rep();
```

I think the difficulty comes from that the underlying type of fixed_point isn't the raw int16_t here, but the overflow safe elastic type.
from_rep and to_rep only go one level deeper and not all the way to the bottom to reach the `int16_t`.

What am I overlooking?

**Comment by johnmcfarlane** [comment]
Hi @elcojacobs. Thanks for the feedback and glad to hear you find CNL useful.

You are correct that `to_rep` only goes one level down and so cannot reliably be used this way. I'm adding functions, `cnl::unwrap` and `cnl::wrap` which are basically multi-level `to_rep` and `from_rep`. I am not 100% certain of their usefulness: your type is trivial (at least as far as Clang and GCC are concerned) so you could simply `memcpy` the contents in and out. However, I appreciate that the protoc-generated API passes by value and so receiving and returning `int16_t` makes for cleaner code.

**Comment by elcojacobs** [comment]
Thanks for the fast reply, I'll give it a test tomorrow.

Instead of a memcpy I used 2 free functions and reinterpret_cast, but obviously, I'd prefer to avoid such a cast. 

```
constexpr int16_t
to_base(const temp_t& t)
{
    temp_t temp = t;
    int16_t raw = *reinterpret_cast<const int16_t*>(&temp);
    return raw;
}

constexpr temp_t
temp_t_from_base(const int16_t& r)
{
    int16_t raw = r;
    temp_t temp = *reinterpret_cast<const temp_t*>(&raw);
    return temp;
}
```

**Comment by johnmcfarlane** [comment]
`wrap` and `unwrap` should replace these but for future reference, using [`std::memcpy`](https://en.cppreference.com/w/cpp/language/reinterpret_cast) instead of `reinterpret_cast` can help you avoid undefined behavior.

**Comment by elcojacobs** [comment]
The wrap and unwrap functions work exactly as expected and have a nice type-safe interface. Thanks!
