### ISSUE TITLE
Multiplication Promotion Rules

### ISSUE THREAD

**Issue by senevoldsen** [johnmcfarlane/cnl#371]
I am having some trouble with multiplying fixed point numbers using Visual C++. The result is supposed to "auto-widen", but does not do this for 32 bit integers, but the decimal point is still moved, and can even be outside the underlying integer value. Same for `<int64, 48>` fixed point multiplied by a `<int32, 24>` results in `<int64, 72>`. This is some observations:

    constexpr int sizeofInt = sizeof(int); // == 4
    constexpr int sizeofInt32_t = sizeof(int32_t); // == 4

    cnl::fixed_point<int32_t, -24> a1{ 0.125 };
    // Because of integer promotion, below type is <int, -48>
    // Expected either <int/int32_t, -24> (with maybe large loss of accuracy) or <int64, -48> 
    auto aa1 = a1 * a1;
    std::cout << "aa1: " << aa1 << std::endl; // outputs "aa1: 0"

    // Result type is <int64_t, -48>
    auto aa2 = cnl::fixed_point<int64_t, -24>(a1) * a1;
    std::cout << "aa2: " << aa2 << std::endl; // outputs "aa2: 0.015625"

    // Result type is <int, -48>
    // Triggers std::terminate at runtime, line 22, in file cnl/_impl/terminate.h
    auto aa3 = cnl::multiply(cnl::saturated_overflow, a1, a1);
    std::cout << "aa3: " << aa3 << std::endl; // outputs "aa3: digit[0]<10" 

I am not that familiar with the intricacies of limited precision math - I mostly need the deterministic consistency across platforms, and not so much high precision - but this does not seem right. In the case that I am wrong, is there anyway to get the desired multiplication result, or specify the desired result type and precision, e.g. somehow get a `fixed_point<int64, -48>`, or a `<int32, -24>` with a close result in `aa1`?

Thanks for the library.

**Comment by senevoldsen** [comment]
@johnmcfarlane

Maybe my experience will be useful when revising the documentation:

Maybe I read a bit too quickly, but from "Arithmetic Functions" https://johnmcfarlane.github.io/cnl/#advanced_arithmetic , I got the impression it would "upgrade" the underlying representation to at least `int` but not stop there. In hindsight, it is now clear that it follows ordinary promotion rules.

Then my misunderstanding, was that it seemed CNL preferred keeping the least significant bits, eg. `fixed_point<int, -24>` with `int = int32_t` squared became `fixed_point<int, -48>`. After brief moment of thinking now, that type itself does make sense I guess. Though it would be wrong to say it has `48` fractional bits, it can indeed represent a number in `2^-48` - is this correct? So my next thought was, that why would CNL keep all the least significant bits and not the most, but after some more thinking it became clear that is my responsibility for dealing with overflow - and now also clear why I got the overflow in the first place. The hint for that compiler flag will be very useful.

I don't actually need "auto-widening", just the ability to control it myself, so I would prefer avoiding it (does it do dynamic allocation?).

So given these types:

    using fp32 = typename cnl::fixed_point<int32_t, -24>;
    using fp64 = typename cnl::fixed_point<int64_t, -24>;

And assuming I use at most 7 bits of "whole integers", is this a correct way to handle my original problem?

    fp32 a{ 0.125 };
    // Temporarily into larger size for multiplication and other calculations
    fp64 a_64 = a;
    // Assuming "whole integer" result part withs in 7 bits
    // This will also preserve the 24 most significant fractional bits??
    fp32 aa = a_64 * a_64;

I don't know about the use case of others, but a "recipe" for how to take a lower precision number, take it into higher precision temporarily, and then put it back in lower precision again, keeping the most significant digits (the analogue of a float to double, do some math, and put result back in float again). 

I think all my use case will need at most 64 bit representation, but is there a limitation on the maximum underlying integer type, e.g. like 64 bit or 128 bit? I saw a DEFINE for 128 bits.

Thanks

**Comment by johnmcfarlane** [comment]
Yes, very helpful. Thank you. I think that what I should put on the front page of the documentation is a table of required properties (e.g. promotion, fractions, overflow etc.) and the types/build flags that satisfy those properties.

To answer your questions: no there is no dynamic allocation. Yes, if you use 64-bit GCC/Clang then there is a 128-bit type. There is also a `cnl::wide_integer` but it isn't very stable yet: slow and not well enough tested.

You can get by by performing your own conversions. Here is [your code running correctly in Wandbox](https://wandbox.org/permlink/71mWldxb9F0txYPg). And here is [the assembler it produces](https://godbolt.org/z/EF99R0). 

But if it's a recipe you're after, then `cnl::elastic_integer` is the type I'd recommend. If you try and preserve the high bits, you'll generally find you lose all your precision. Better to convert back to the original type in this case. Here is [the same code using `elastic_integer` to figure out the promotion and conversion for you](https://godbolt.org/z/bTukOt). Note it's the same assembler as the hand-rolled version.

Finally, the code will be more efficient if you don't use negative values. One way to do this is to [use unsigned integers](https://godbolt.org/z/D-saJj). Another is to [enforce a precondition using contracts](https://godbolt.org/z/qcn4ng).

I'll close this issue once the documentation is up to date.

**Comment by johnmcfarlane** [comment]
The front page of the documentation is rewritten. The [example](0e84ac88e612237c4660b06e5a2a23e788c08ba5
https://johnmcfarlane.github.io/cnl/index.html#Arithmetic_Functions) has been reworded and reference to free function, `std::multiply` is gone in #373. Thanks again for the feedback.
