### ISSUE TITLE
Wrong case for CnlConfig.cmake.

### ISSUE THREAD

**Issue by Strasser-Pablo** [johnmcfarlane/cnl#383]
Hi,
On linux the file CnlConfig.cmake has a wrong name, it need to be named cnlConfig.cmake or cmake will not find it.
Leading to the following error message:
`Could not find a package configuration file provided by "cnl" with any of
  the following names:

    cnlConfig.cmake
    cnl-config.cmake
`

**Comment by johnmcfarlane** [comment]
Did you use the `find_package` command? If so was the name `cnl` or `Cnl`? The former works on Linux in [this example](https://github.com/johnmcfarlane/cnl_example/blob/master/CMakeLists.txt).

**Comment by Strasser-Pablo** [comment]
Yeah I used find_package(cnl) .
Maybe this is the reason.

**Comment by johnmcfarlane** [comment]
Let me know if that doesn't fix it. Leaving this issue open so I remember to mention the example project in the docs.

**Comment by Strasser-Pablo** [comment]
Ok confirmed it works.

**Comment by johnmcfarlane** [comment]
The [README](https://github.com/johnmcfarlane/cnl/blob/develop/README.md) now mentions the [example project](https://github.com/johnmcfarlane/cnl_example). Thanks again for your feedback.
