### ISSUE TITLE
CDSP break #1: cnl::convert

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#414]
Need to reinstate free functions.

**Comment by johnmcfarlane** [comment]
Break happened in [b3dd279](https://github.com/johnmcfarlane/cnl/pull/391/commits/b3dd279ed402c134047d8d90782b1d066157d917) in #391.

**Comment by johnmcfarlane** [comment]
Existing free functions are not implemented consistently. I've set up [a poll](https://twitter.com/JSAMcFarlane/status/1117434724790808576) to see what ppl prefer. @hbe72 and @vanossj please feel free to chime in with an opinion.

**Comment by hbe72** [comment]
Chimed ;). I prefer that the target type and conversion parameters or "rules" are template parameters.

**Comment by johnmcfarlane** [comment]
Merged. PR to CDSP is [#9](https://github.com/hbe72/cdsp/pull/9).
