### ISSUE TITLE
numeric_limits::lowest() off by 1 bit?

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#426]
I encountered an unexpected result while running my tests:

``` cpp
template <
    int IntegerDigits,
    int FractionalDigits,
    class Narrowest>
using saturated_elastic_fixed_point = cnl::fixed_point<
    cnl::elastic_integer<
        IntegerDigits + FractionalDigits,
        cnl::rounding_integer<
            cnl::overflow_integer<
                Narrowest,
                cnl::saturated_overflow_tag>,
            cnl::native_rounding_tag>>,
    -FractionalDigits>;


using temp_t = saturated_elastic_fixed_point<7, 8, int16_t>;
using temp_precise_t = saturated_elastic_fixed_point<7, 23, int32_t>;
using temp_wide_t = saturated_elastic_fixed_point<23, 8, int32_t>;

    WHEN("conversion_to_small_precision")
    {
        // non-clipping/non-overflowing conversion
        temp_wide_t tw = 0.5;
        temp_t t = tw;
        CHECK(t == temp_t(0.5));

        // clipping conversion should be constrained to min/max
        tw = -150;
        t = tw;
        temp_t lowest = cnl::numeric_limits<temp_t>::lowest();
        CHECK(t == lowest);

        CHECK(cnl::unwrap(t) == cnl::unwrap(lowest));

        tw = 150;
        t = tw;
        CHECK(t == cnl::numeric_limits<temp_t>::max());
    }

```

`cnl::unwrap(cnl::numeric_limits<temp_t>::lowest())` returns -32767, instead of -32768. 

The value is truncated to the minimum representable by int16_t as expected. Is my interpretation of what lowest() should do wrong or is this a bug?

In other words:
`cnl::unwrap(cnl::numeric_limits<temp_t>::lowest())` is not equal to `std::numeric_limits<int16_t>::lowest());`

**Comment by johnmcfarlane** [comment]
The code is doing the right thing but the `temp_t`'s limit is being exceeded. The problem is that `overflow_integer` wraps an `int32_t` -- not `elastic_integer` -- so when the value exceeds its range, `overflow_integer` caps at `int32_t`'s range and not `elastic_integer`'s.

Wrap the `elastic_integer` inside the `overflow_integer` in order for the value to be correctly capped. Better still, [use `static_number`](https://github.com/johnmcfarlane/cnl/pull/427/files#diff-b4a382e2495f8dd25eebfbcac82cf1f1R9) which is ready-built for this purpose.

**Comment by elcojacobs** [comment]
Thank you for your quick support once again. `static_number` looks great and I didn't notice it had been added.
How all these types can wrap each other and how the order affects things would be a nice addition to the documentation.
I browse the test cases more than the docs to try to figure out the possibilities. They contain many example composite numbers that would be great in a docs overview.

In my case, I want my calculations to be elastic (widen for intermediate results with 'auto' type), but I want values to round and saturate when assigned to a smaller type.

I noticed that when the template is expanded to include `Narrowest`, compile errors arise when `int16_t` is used. Just initialization from double is enough.
I don't use an `iint16_t` integer in my application, only in a test case. So this doesn't really affect me, just letting you know.

Example:
```cpp
template <
    int IntegerDigits,
    int FractionalDigits,
    class Narrowest>
using saturated_elastic_fixed_point = cnl::static_number<
    IntegerDigits + FractionalDigits, -FractionalDigits, cnl::native_rounding_tag, cnl::saturated_overflow_tag, Narrowest>;

using temp_t = saturated_elastic_fixed_point<7, 8, std::int16_t>;
temp_t a = 5.0;
```

**Comment by johnmcfarlane** [comment]
Unfortunately, I'm not able to reproduce this. For example with a recent version [here](https://godbolt.org/z/ZE_aXb). Can you give me more details of how to produce the error and what the output is?

**Comment by elcojacobs** [comment]
Hi John, I tried to reproduce it on Godbolt, then found out that I was not on the latest develop release of CNL for my cnl submodule. Compiles with CNL at develop. Sorry for the false alarm, seems to be fixed already. Other bugs seem to have been introduced, but I'll create a separate issue for that.

**Comment by johnmcfarlane** [comment]
No problem. Thanks for all the feedback. I will have a think about how to
make composition easier to achieve - probably staying with better examples
on the front page.
