### ISSUE TITLE
Incorrect result in conversion of static_number that increases fraction bits

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#429]
Latest develop seem to introduce errors when converting a static_number to a static number with more fraction bits.

I hope this godbolt demo shows the issue clearly.
https://gcc.godbolt.org/z/caXsQW

**Comment by johnmcfarlane** [comment]
This should be fixed now. Sorry for the delay, this was quite a juicy problem!

**Comment by johnmcfarlane** [comment]
https://gcc.godbolt.org/z/es9ufR

**Comment by johnmcfarlane** [comment]
https://gcc.godbolt.org/z/STlYYP
