### ISSUE TITLE
Printing Fixed Point Numbers

### ISSUE THREAD

**Issue by nelsontodd** [johnmcfarlane/cnl#486]
Hi,

I am getting strange behavior with cout. When I declare a fixed point number with an exponent larger than the width of the rep, `cout << x << endl;` will print 0.9999904632568359375 which is 1-5*2^-19. I believe (Or Davis believes) that the issue might be somewhere in `to_chars.h`. Here is an example:

`cnl::fixed_point<cnl::elastic_integer<>, -40> dt = .00000000005;`
`cout<<dt<<endl;`

Will print 0.9999904632568359375 for some reason. Am I doing something wrong? Or is this a bug, as Davis suggested. 

Nelson

**Comment by johnmcfarlane** [comment]
Yes, quite likely a bug.

Printing in a different base with all edge cases covered is notoriously
difficult and with no effective bounds on the exponent, my method of
printing could potentially use gigs of stack space even if it were bug
free!

As a workaround, convert to floating point before printing.

Also a general rule: if I'm not proposing it, my implementation may well be
incomplete as the potential work involved with getting fixed point up to
par with floating point library support is considerable.

Thanks for the feedback.

**Comment by nelsontodd** [comment]
Ok. No problem. Thank you!

**Comment by johnmcfarlane** [comment]
Note to self: answers [here](https://stackoverflow.com/q/57452174/671509) may provide ideas on how to reduce edge cases with simpler algorithm.

**Comment by johnmcfarlane** [comment]
Note to self: it may be possible to adapt [this algorithm](https://github.com/jk-jeon/dragonbox) to extract the exponent and significand necessary to reliably print `scaled_integer` values.

**Comment by johnmcfarlane** [comment]
[v2.x repro](https://godbolt.org/z/q31nK587P)

**Comment by johnmcfarlane** [comment]
@nelsontodd this is fixed now. The algorithm truncates results, so is less accurate than it could be. (`rounding_integer` [appears to do a good job](https://godbolt.org/z/b87an17ze) of mitigating this.)
