### ISSUE TITLE
Variables named "near" and "far" may cause trouble under some windows environments

### ISSUE THREAD

**Issue by burnpanck** [johnmcfarlane/cnl#512]
Compiling some moderately large C++17 code-base using MinGW for windows, I ran into compilation issues with `cnl/_impl/fraction/make_fraction.h`, because the lambda at around line 72 uses function arguments named  `near` and `far`. As it happens, in my configuration, those two words are `#defined` to expand to nothing, because apparently in ancient times they were used as non-standard attributes to distinguish near and far pointers. The offending definition gets included in my environment through `windows.h` > `windef.h` > `minwindef.h`. Unfortunately `WIN32_LEAN_AND_MEAN` does not prevent that definition.
It's astonishing that the we still have to cope with such blatant violation of the global namespace by system headers, and by no means is that something I agree with. Nonetheless, in this case it's easy enough to name those variables slightly different and possibly prevent some headaches for those poor fellas like me who have to work with windows from time to time.

**Comment by johnmcfarlane** [comment]
I remember memory segments all too well so you have my sympathy! That should be fixed now.
