### ISSUE TITLE
Multiplication by int is not optimized and creates slow large binary

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#523]
I have isolated the inlining/optimization failure in a simpler example.
Calculations like this seem to be the cause of the bloated/slow binary of issue #521 

```cpp
#include <cnl/static_number.h>


template <
    int Digits,
    int Exponent,
    typename Narrowest = signed>
using safe_elastic_fixed_point = cnl::static_number<Digits, Exponent, cnl::native_rounding_tag, cnl::saturated_overflow_tag, Narrowest>;

int main() {  
    safe_elastic_fixed_point<23, -12> a = 800;
    safe_elastic_fixed_point<23, -12> b = 400;
    safe_elastic_fixed_point<23, -12> c = 200;


    // the line below renerates a program output of 6 (correct) in 2 lines of assembly
    // auto result = ((a + b) / c);
        
    // the line below generates a program output of 18 (correct) but a huge binary
    auto result = ((a + b) / c) * 3;

    // decltype(a):: x; // use compiler error to check type, it uses cnl::power<-12,2>
    // decltype(result):: y; // use compiler error to check type, it uses cnl::power<>
    
    int asInt = static_cast<int>(result);
    return asInt;
}
```

https://godbolt.org/z/UpMv3c

**Comment by elcojacobs** [comment]
Expanded example:
```
#include <cnl/static_number.h>


template <
    int Digits,
    int Exponent,
    typename Narrowest = signed>
using safe_elastic_fixed_point = cnl::static_number<Digits, Exponent, cnl::native_rounding_tag, cnl::saturated_overflow_tag, Narrowest>;

int main() {  
    safe_elastic_fixed_point<23, -12> a = 800;
    safe_elastic_fixed_point<23, -12> b = 400;
    safe_elastic_fixed_point<23, -12> c = 200;
    safe_elastic_fixed_point<23, -12> d = 3;
    int e = 3;
    int8_t f = 3;

      
    // the line below generates a program output of 18 (correct) but a huge binary
    // auto result = ((a + b) / c) * 3;

    // the line below generates a program output of 18 (correct) but a huge binary
    // auto result = ((a + b) / c) * e;

    // the line below generates a program output of 18 (correct) in 2 lines of assembly
    auto result = ((a + b) / c) * f;

    // the line below generates a program output of 18 (correct) in 2 lines of assembly
    // auto result = ((a + b) / c) * safe_elastic_fixed_point<23, -12>(3);

    // the line below generates a program output of 18 (correct) in 2 lines of assembly
    // auto result = ((a + b) / c) * d;

    // decltype(a):: x; // use compiler error to check type, it uses cnl::power<-12,2>
    // decltype(result):: y; // use compiler error to check type, it uses cnl::power<>
    
    int asInt = static_cast<int>(result);
    return asInt;
}

```
https://godbolt.org/z/_ZxGk9

As you can see, the multiplication with int8_t can be optimized, so the potential for overflow seems to be related.

**Comment by elcojacobs** [comment]
Another demo:

Compiles to single instruction:
```
auto result = ((a + b) / c) + ((a + b) / c)  + ((a + b) / c) ;
```
Compiles to 943 lines of assembly:
```
auto result = 3 * ((a + b) / c) ;
```

**Comment by johnmcfarlane** [comment]
Try using constant<3>{}. It's narrower. Int is effectively a <31, 0> fixed
point number. That means the result of using it in multiplication is many
more integer digits. The result has to be wide enough that INT_MAX * ...
would also fit and that is probably causing the result to be multi-word
which is not yet optimised.

**Comment by elcojacobs** [comment]
Sorry to say that `auto f = int8_t(3);` results in a 2 line binary, but `auto f = cnl::constant<3>{};` creates a binary of 943 lines.

**Comment by johnmcfarlane** [comment]
Hi @elcojacobs I'm doing a bit of triage after a round up changes. The CE examples seem to reduce down to two instructions now.

* First example with latest GCC: https://godbolt.org/z/f4oeWr
* Second (expanded) example with latest GCC: https://godbolt.org/z/qshb9z

I'll be closing this issue in the near future unless you wanted to a further look at it.

**Comment by elcojacobs** [comment]
Hi John,

That's great. I am not at the latest version at the moment, but it works and I am not touching it.
Good to see you are making progress and I will try out your latest release when I have a bit more time on my hands.

And thanks for retweeting a tweet by Carlos (@CvRXX), about him looking for a cool C++ internship. I was surprised to find out he lived in the Netherlands and I sent him a message. He is starting on Monday! Small world :+1:

**Comment by johnmcfarlane** [comment]
Wow, so glad I could be of help!
