### ISSUE TITLE
Fixed point divide returns value rounded to integer equivalent (no fractional digits)

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#524]
In this simple calculation with 3 fixed-point values, the fractional bits are lost.
The result should be 1365, but 4096 (equivalent of 1.0) is returned.

```cpp
#include <cnl/static_number.h>


template <
    int Digits,
    int Exponent,
    typename Narrowest = signed>
using safe_elastic_fixed_point = cnl::static_number<Digits, Exponent, cnl::native_rounding_tag, cnl::saturated_overflow_tag, Narrowest>;

int main() {  
    safe_elastic_fixed_point<12, -12> a = 10;
    safe_elastic_fixed_point<12, -12> b = 30;
    
    auto result = safe_elastic_fixed_point<23, -12>(a/b);

    // correct answer would be: 
    // auto result = safe_elastic_fixed_point<23, -12>(10.0/30.0);
    
    int asInt = cnl::unwrap(result);
    return asInt;
}
``` 

Reproduced on Godbolt:
https://godbolt.org/z/a7snhY

**Comment by johnmcfarlane** [comment]
Division for integers is different than for floating-point so the result
here is hey different. When dividing, the exponent of the result is
exponent of LHS minus exponent of RHS.

If you want fractional digits, either convert LSH to something with lower
exponent or RHS to something with higher exponent. Alternatively, use the
modulo operator to capture the remainder or use the quotient function:
https://github.com/johnmcfarlane/cnl/blob/master/include/cnl/_impl/scaled_integer/named.h#L109

**Comment by elcojacobs** [comment]
Are you sure this is how you want the library to work? It is different from an earlier version.

If the CNL fixed point class is intended to replace floating point, I would expect 10.0/30.0 to return 0.33 and not 1.0.

**Comment by elcojacobs** [comment]
Btw, the quotient function results in 1.0 too.

**Comment by johnmcfarlane** [comment]
It's been this way for quite some time. Unfortunately it's a tough design
space to navigate.

Fixed-point cannot fully replace floating-point. You cannot represent .33
in binary with either system. With floats, you get an approximation that is
optimised at run time. Fixed point does not have that luxury: you need to
decide via the type system how much precision you can afford before the
program is compiled.

The quotient function gives you the ability to choose your precision or
tries to guess for you. Alternatively, initialising with the fraction type
gets the same result from C++17 onward. Here's an example
<https://godbolt.org/z/Z78GfE>.

I'm likely to implement a variation of fixed-point that tries to act more
like float in the future but it will still have surprising corner cases and
will involve wider results and run-time shifts. It will only provide a
limited subset of existing functionally wrapped in an easier API.

**Comment by johnmcfarlane** [comment]
Regarding your problem with quotient, it could be because you have no integer digits. Here's [an example of quotient](https://godbolt.org/z/sEeWTc).

**Comment by elcojacobs** [comment]
Here is what I expect would happen:

I am dividing two values with 12 integer, 12 fraction bits and a sign bit. The result can be presented without friction loss by a 45,-24 fixed point value.
So `auto c = a/b` should return a 45 bits wide integer with exponent -24. When I assign that to a 23, -12 type, it should saturate/truncate to fit.

This seems to be what happens when an intermediate auto variable is used to store the widened type, but not when a smaller type is constructed from an rvalue reference.

Is the constructor or copy constructor missing for an rvalue ref of a widened type?

https://godbolt.org/z/nUpurW

**Comment by elcojacobs** [comment]
Sorry, it's early in the morning, I interpreted my results wrong.
I think it can be summarized in that I expect the divide operator to be an alias for cnl::quotient.

What is your reasoning for not doing that?
I could not find in the docs why cnl::divide and cnl::quotient both exist and what their intended use case is.

**Comment by johnmcfarlane** [comment]
`cnl::divide` is equivalent to `operator/`. It performs no shifts and is lossless so long as the denominator is not zero. By lossless, I mean that if you take the quotient and remainder using `operator/` and `operator%`, you can work back to the numerator:

    auto q = nume / denom;
    auto r = nume % denom;
    auto nume_derived = q * denom + r;

You are not guaranteed to be able to do that with floating-point division or `cnl::quotient`.

`cnl::quotient` attempts to guess what precision you might want unless you specify otherwise. If it's possible to get a lossless result, I think you'll be able to do that. For example `1 / 4` will produce a result with at least two fractional digits. However, it still cannot provide lossless quotients under all circumstances. The obvious example is that it cannot represent `1 / 3` using binary radix types. Shifting *and* widening occur in order to fulfill those guarantees. The only exception is that if the denominator has `Exponent==0`, then no shift is necessary.

**Comment by johnmcfarlane** [comment]
The quasi-exact `operator/` is captured now in #788 so I don't think there's any more reason to leave this discussion open.

**Comment by johnmcfarlane** [comment]
Division now [explained](https://johnmcfarlane.github.io/cnl/index.html#division) in the FAQ.
