### ISSUE TITLE
Overflow termination with saturate overflow tag

### ISSUE THREAD

**Issue by elcojacobs** [johnmcfarlane/cnl#529]
I got this SIGABORT termination that I did not expect:

https://godbolt.org/z/KQmWrN

Perhaps the saturate tag is not passed down correctly to one of the templates?

**Comment by johnmcfarlane** [comment]
It's an assert firing in `duplex_integer` as the calculation exceeds 63-bit boundary. Here is [the same example with 128-bit integers enabled](https://godbolt.org/z/FeyHBb). 

`duplex_integer`, the multi-word integer, is still a work in progress (and the most complex type to maintain). 

Do you require multi-word or would you rather avoid such calculations via other means such as narrowing intermediate values? If the latter, you can eliminate `duplex_integer` and replace run-time errors with compiler errors:

```c++
template <
        int Digits,
        int Exponent,
        typename Narrowest = signed>
using safe_elastic_fixed_point =
cnl::scaled_integer<
        overflow_integer<
                elastic_integer<
                        Digits,
                        rounding_integer<
                                int,
                                cnl::nearest_rounding_tag>>,
                cnl::saturated_overflow_tag>,
        cnl::power<Exponent>>;
```

**Comment by elcojacobs** [comment]
I can limit intermediate results to 64 bits, if by a word you mean 64 bits (it is probably 32 on my platform).
I would even prefer that over the costs of 128 bit calculations.

In trying your solution, I get new unexpected results:

https://godbolt.org/z/YYUMt6

That conversion should not need 64 bits, as the commented "get type through compiler error" shows, the type is only 32 bits wide. It should not need 32 extra bits for rounding.

Can you explain why the order is scaled<overflow<elastic<rounding>>>?
I understand that overflow should the outer one and should only occur when elasticity limits are hit.

But can you explain what swapping elastic and round would do?
It doesn't help with the error though: https://godbolt.org/z/KSxDBx

**Comment by johnmcfarlane** [comment]
Tracking the issue in #530. That shouldn't happen.

However, this calculation certainly needs more than 31 digits because `v2` is scaled to the same exponent as `v1` before they are added. That effectively makes the LHS `safe_elastic_fixed_point<31, -20>`. Then when they are added, the operands need to be widened by a further bit to accommodate the result.

The nesting of the types is an interesting topic. I think that the swap you suggest would result in wider intermediate types. Ultimately, I'd like all combinations to work. Then I could test and measure the relative benefits of each. But as you can see, it's a lot of work to make a fully generic component type.

**Comment by elcojacobs** [comment]
I know, the widening is expected and correct, but not all the way to 64 bit. I see you created an issue for it. Thanks.
I can definitely see this library is a lot of work and incredibly complex. I have huge respect for your work. Templates going this deep are not easy to debug and optimize.
I hope all the issues I create are welcomed and help you improve the library.

**Comment by johnmcfarlane** [comment]
No certainly not 64 digits, i.e. 65 bits. That's what #530 is for. 

But I do think that 32 digits (i.e. 33 bits) are needed to hold that result without risk of overflow. That requires an `int64_t`. (I don't count the sign bit as a digit.)

**Comment by elcojacobs** [comment]
Yes, to be specific: the compiler error occurs when the number the max integer bits and max exponent bits of both operands add up to over 32.

**Comment by johnmcfarlane** [comment]
Closing this as it's tracked in #530
