### ISSUE TITLE
Scaled_integer is broken when constructing from int while internal representation is int64_t

### ISSUE THREAD

**Issue by liarokapisv** [johnmcfarlane/cnl#576]
It appears that `scaled_integert` does not correctly handle initialization from integers when the Rep type is `int64_t`:

```
using fixed = cnl::fixed_point<int64_t, -25>;

fixed test1(64);
// broken prints negative
std::cout << test1 << std::endl;

fixed test2(int64_t(64));
// correct
std::cout << test2 << std::endl
```

After digging in the problem seems to be due to `cnl::_impl::from_value<Dest, Srct>` forwarding to `cnl::_impl::from_value<Src, Src>` when `Src` is an integer: 
https://github.com/johnmcfarlane/cnl/blob/fcd79848741008a828ab7010149f61dda7728e54/include/cnl/_impl/num_traits/from_value.h#L35-L39

This forces the `convert_operator` to pass to `cnl::_impl::scale` a value of the `Input` type instead of the `Result` type:

https://github.com/johnmcfarlane/cnl/blob/fcd79848741008a828ab7010149f61dda7728e54/include/cnl/_impl/scaled/convert_operator.h#L53-L67

This in turn leads to initializing the underlying `Rep` value by the possibly overflowed scaled input expression. In the above example the underlying `int64_t` value is initialized by an overflowed `(int)64 << 25` expression.

**Comment by johnmcfarlane** [comment]
Conversion to scaled_integer involves scaling the input then converting to the rep type. The alternative would be converting to the rep type and then scaling which would introduce complementary cases of overflow, e.g. when passing 0x100000000LL to `scaled_integer<int, power<32>>`.

And then there are powers which guarantee overflow with any combination of values and fundamental integer type. They also often involve compiler errors as the integer needs to be shifted by more bits than it has, e.g. [`42 << 32`](https://godbolt.org/z/dFW7j6). For this reason, I recommend initialising using a floating-point value. 

Another reason for this design: the API needs to suit `rep` types which avoid overflow in various ways, esp. `elastic_integer`. Really, the type is designed so that if you want to reduce the incident of overflow in easily-avoidable cases, `elastic_integer` is a good choice.

**Comment by liarokapisv** [comment]
I understand that this is a difficult design space but I would like to make a case for why in my opinion this is a problematic decision.

Most numeric types, both builtin and library ones that allow /implicit/ conversions, do what one expects. They attempt to approximate the given value as long as it is within the representable domain. This is true for builtin integer types, for floating_point/integer conversions and for other other popular libraries like boost. 

Scaled_integer is just that, an integer scaled by a specific term.
This means that we can deterministically know the domain that it can represent.
It also allows /implicit/ conversions from floats and integer. It does the expected thing when using floats but not when using integers. This is very surprising and can lead to bugs.

In the original example we use a type able to represent 2^64 multiples of 2^(-25). As such one would expect to be able to use integer literals of [0,2^38]. This is supported by the fact that one may do so with floating point literals and using integer literals also works fine when the underlying type is just int. Instead we are restricted with just integer literals of the range [0,32] while everything else silently overflows.

In any case, I think that having a better default integer literal behavior would benefit the library a lot.

At the very least I think that this should be documented and/or the implicit conversion should be removed if it stays like this because with the current behavior it is very error-prone. 

Another approach would be to have a "smarter" conversion sequence for builtin-integers that takes overflow and underflow into account. Maybe it could choose between the different representations according to the power provided.

**Comment by johnmcfarlane** [comment]
> Most numeric types, both builtin and library ones that allow /implicit/ conversions, do what one expects. They attempt to approximate the given value as long as it is within the representable domain. This is true for builtin integer types, for floating_point/integer conversions and for other other popular libraries like boost.

I'll assume we agree that the library without implicit conversions would be become unreachable very quickly.

> Scaled_integer is just that, an integer scaled by a specific term.
This means that we can deterministically know the domain that it can represent.
It also allows /implicit/ conversions from floats and integer. It does the expected thing when using floats but not when using integers. This is very surprising and can lead to bugs.

That's a very good point. A problem is that this affects the behaviour of the type based on a rather complicated interplay between all the template parameters and the initializer type. This is equally surprising for users who: start to tweak their exponents; observe inconsistent results in generic functions specialized on differerent types; or change an expression (e.g. between `+` and `*`) and are baffled when it 'stops working'.

Partly, these are limitations in C++11, 14 and 17. You cannot overload a constructor on the `explicit` specifier. [In C++20, explicit takes a condition](https://en.cppreference.com/w/cpp/language/explicit). That allows us to introduce this surprising behaviour. But it is still surprising. (And limits the library to C++20. Hence my interested in what version of C++ users target.) Concepts may also make the error messages easier to understand. This is very important as the current error messages are terrible!

> ...and using integer literals also works fine when the underlying type is just int.

Ah, [but is that strictly true](https://godbolt.org/z/4FRTgn)? With scaling, conversion becomes a deceptively complicated operation. You, personally, have a pretty good handle on it. You would not be surprised if you cannot assign `64` to `fixed_point<int, -25>`. But you are somewhere along a spectrum of understanding about the nature of this type.

Where along this spectrum should we assume a novice/casual user lies? I have opted for an extreme that takes in readability and performance. It deprioritizes writability and safety. I have then provided additional features which layer writability and safety on top:

* [Example of safe use using `elastic_integer`](https://godbolt.org/z/x8TZUN).
* [Example of safe use using `overflow_integer`](https://godbolt.org/z/vKu6pt).

> At the very least I think that this should be documented and/or the implicit conversion should be removed if it stays like this because with the current behavior it is very error-prone.

***Action***: put a detailed note in the documentation for `scaled_integer` and/or `scaled_integer::scaled_integer` which warns about out-of-range errors and recommends solutions.
***Action***: #93 revisits `explicit` and should take this conversation into account.
***Action***: #553 helps avoid this issue efficiently. Make sure that it is encouraged throughout the documentation once it is implemented.

> Another approach would be to have a "smarter" conversion sequence for builtin-integers that takes overflow and underflow into account. Maybe it could choose between the different representations according to the power provided.

I believe that [`elastic_integer`](https://godbolt.org/z/x8TZUN) largely accounts for the overflow discussed here. (Point of note: I think you mean negative overflow, not underflow.)

> Finally I also want to make the case for embedded systems where the integer conversion is much faster than the floating point one, in fact the floating point conversion turned out to be too slow for on-the-fly computation while integer literal conversions where acceptable compared to obfuscating mathematical formulas by using constants.

For compile-time literals, float should impose [no penalty](https://godbolt.org/z/tGsHYw). For 32-bit architectures, always converting to 64-bit integers *just in case* the value is too great will probably impose a penalty which the user might not need to pay. If a user aims for maximum performance, I recommend testing code in a sanitizer using [`overflow_integer`](https://godbolt.org/z/vKu6pt) to fully understand where performance needs to be sacrificed. Using tools which uncover issues at development time is the only way to avoid additional cost in production code.

It's a hard line to take but it's the only way to serve everybody. But I need to make this much, much clearer in the documentation. Thanks for making this clearer to me.

**Comment by liarokapisv** [comment]
I actually just realized that this works fine when using elastic and overflow integer. These are treated specially compared to normal integers when initializing. I was under the impression that the difference in these types had to do with their operations, not with their initialization. This is a sane solution but I think it's definitely worth taking the time to better explain in the documentation. In any case thanks for taking the time to read all of this. I am really looking forward to see the direction the library will take in the future!

**Comment by johnmcfarlane** [comment]
With merging of #598 all remaining action items are covered in other issues.
