### ISSUE TITLE
Drop support for C++11, C++14 and C++17

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#608]
This is primarily in order to move to concepts as a replacement for SFINAE. Other advantages include:
* removal of `make_` functions in favour of CTAD. (C++17)
* removal of `-> decltype(function-body)` from function declarations. (C++14)
* removal of recursive `constexpr` functions. (C++14)
* better control of explicit constructors. (C++20)

Additional things that might be worth investigating:
* <=>
* feature test macros
* bit functions

**Comment by danieagle** [comment]
Just to inform. :-)
My  C++ programs have been using C++20 for a long time and
-std=c++20 is my default target in g++-10. because this, I'm don't care 
too much in working with old standards.
Thanks For CNL e Cia. :1st_place_medal:

**Comment by johnmcfarlane** [comment]
@danieagle thanks for the data point!

**Comment by johnmcfarlane** [comment]
Fixed in #648
