### ISSUE TITLE
How catch exceptions in math operations ?

### ISSUE THREAD

**Issue by danieagle** [johnmcfarlane/cnl#635]
Hi!
How I can catch overflow/underflow norrowing exceptions ?

https://godbolt.org/z/Ecafn4

the actual behavior is just terminate the whole program. :-)
I need your guidance! :-)

Really Thanks in Advance!

[]'s Dani.

p.s: Really Thanks for this lib!

**Comment by johnmcfarlane** [comment]
Hi Dani. Thanks for getting in touch.
Firstly, the tag for invoking exceptions is `cnl::throwing_overflow_tag`, not `cnl::trapping_overflow_tag`.
Secondly, my wide integer implementation still has some issues. It's one of the most challenging types I've attempted to add to the library and it still has bugs so even that tag will result in a trap operation currently.
One other note about exceptions: they must not escape the `main` function. If you intend for an exception to be thrown in your program, always make sure it is caught somewhere.

*Actions*:
* Leave this issue open until [this example](https://godbolt.org/z/b5r3Mv) compiles. 
* #636 added to address related compiler error.

**Comment by johnmcfarlane** [comment]
BTW, by underflow, I assume you mean negative overflow.

**Comment by danieagle** [comment]
Hi!
  Thanks for the response!
  Cnl is THE lib of my dreams. this posseses integer, float(escaled integer) 
  and fracional(rational). the fixed point is another big get(!) Because I can insert the number is a file in a previsible maner.
  For catching, your example is o wath want.
  I want help you to you help me. :-)  I can send many issues I founded and help as tester. 
  This lib working at full plennum is a dream come true. :-)

  Best God Blesses for you,
  Dani.

**Comment by johnmcfarlane** [comment]
Closing as [this example](https://godbolt.org/z/b5r3Mv) now compiles, although I'm sure there's still work to do here. Please feel free to send other examples of things that might need attention.
