### ISSUE TITLE
check whether type has particular overflow tag or rounding tag

### ISSUE THREAD

**Issue by to-scho** [johnmcfarlane/cnl#651]
Hi John,

is there any trait to check whether a particular cnl type like static number<...> uses a particular overflow or rounding tag?

Regards, Tobias

**Comment by johnmcfarlane** [comment]
Hi Tobias,

It appears that I implemented a general-purpose rounding tag getter ([example](https://godbolt.org/z/bc1sPc)), but not an overflow tag getter. It's easy enough to cobble together ([here](https://godbolt.org/z/KTPMbE)) just by copying all the `rounding` machinery and renaming it `overflow`.

HTH,
John

**Comment by to-scho** [comment]
Thx John, works like a charm. Regards, Tobias
