### ISSUE TITLE
Feature request: saturating arithmetic

### ISSUE THREAD

**Issue by imgod2u** [johnmcfarlane/cnl#653]
The arithmetic in the algorithm I'm using needs to be saturating rather than rollover. For instance, using an internal 32-bit signed integer to represent Q16.16, 2^16-1 + 1 should saturate at 0xFFFF_FFFF.

Could we add a template mode to support this?

**Comment by johnmcfarlane** [comment]
Hi there. So, Q notation is a bit ambiguous but I'd prefer to call a 32-bit signed integer-backed fixed-point number with 16 fractional digits Q15.16, not Q16.16. (Perhaps you're after an *unsigned* Q16.16; I'm not sure.)

When you assign 0x10000 to that type, it will satrate at 0x7fff.ffff. There is a CNL type that can do this, `overflow_integer` using the `saturated_overflow_tag`. ([example](https://godbolt.org/z/Kc5YGv).) Hope that's what you're after.

**Comment by imgod2u** [comment]
Hi John,

I am after 1 sign bit, 15 integer bits and 16 fractional bits.

Thanks for the code snippet. How do I specify fractional bits in overflow_integer?

**Comment by johnmcfarlane** [comment]
Sorry I think I got my CE links in a twist. Here is the type I believe you're after: https://godbolt.org/z/7Wcnq8

**Comment by imgod2u** [comment]
Thanks. Combining this with the previous question I had in another thread, is there a way I can get an elastic_integer and overflow_integer? I'd like both behaviors.

**Comment by johnmcfarlane** [comment]
```c++
scaled_integer<
    overflow_integer<
        elastic_integer<31, int>,
        saturated_overflow_tag>, 
    power<-16>>;
```

**Comment by imgod2u** [comment]
Awesome, thanks!
