### ISSUE TITLE
Setting the base representation to some value

### ISSUE THREAD

**Issue by imgod2u** [johnmcfarlane/cnl#658]
So in the course of debugging for various saturation, truncation, etc. corner cases, I dump out hex representations of my CNL type:
```c++
using q15_16_rep = cnl::elastic_integer<31, int>;
using q15_16_scale = cnl::power<-16>;
using q15_16 =
    cnl::scaled_integer<
        cnl::overflow_integer<q15_16_rep, cnl::saturated_overflow_tag>, 
        q15_16_scale>;
```
When I find cases I want to report, I want to be able to reproduce them in a short test case. At this point, I mostly only know the hex representations of the internal rep value, not the fractional interpretation.

In order to create new cases, I'd like to be able to create a type and set its underlying rep to the hex value. Looking at the documentation, there doesn't seem to be an immediate way to do that. set_rep I believe just converts the underlying data type to some other type.

Is there a good way to do this?

**Comment by keryell** [comment]
That sounds like a good use case.
Kind of hex floating point format for debugging/testing purpose.
Adding a literal suffix for this too?

**Comment by johnmcfarlane** [comment]
@keryell I'm trying to imagine a UDL which would express negative numbers in an intuitive way. @imgod2u is providing examples where the hexadecimal is unsigned but the values are sometimes negative. See how the negative value from the previous issue has completely different hex digits when [hex float literals](https://en.cppreference.com/w/cpp/language/floating_literal) are used: https://godbolt.org/z/Yzb49j

Can there be an intuitive literal given the way that two's complement increments/decrements numbers by 1 when changing sign?

`set_rep` is a meta-function which transforms a type. But here, we're looking to translate the value. Again, it's not public API (another example of #656) but `cnl::_impl::from_rep` sounds like it's the inverse of `to_rep` that is needed here ([example](https://godbolt.org/z/c51e5b)). @imgod2u is that the solution you're looking for?

**Comment by imgod2u** [comment]
@johnmcfarlane Yes that's what I'm attempting to do. Since we're dealing with the underlying format, I was going to manually convert to 32 (or 64) bit 2's complement numbers before storing it.

Typically this happens when I run my program with debug statements and encounter some corner case I need to debug (or reproduce a case for) later. I usually print out the underlying hex representation since that's the best way to correlate to what my program is modeling (hardware).
