### ISSUE TITLE
Fixed point division problem perhaps

### ISSUE THREAD

**Issue by hbe72** [johnmcfarlane/cnl#662]
Hi John,

Would you mind to take a look at recently committed v1_fixed_point_division branch, whether that problem makes sense?

I've been following the discussion you have had with imgod2u. He is pretty much doing similar things that I do.
He needs a specific rounding mode (drop the unnecessary LSB bits) which is the one HW designers understand and usually implement. The second such rounding mode is that tie_to_inf which we did a while back.

I nearly responded, but then checked the cdsp code, and stumbled into a possible cnl bug which I try to minimise.
While doing that I found this simple error now exposed in v1_fixed_point_division.

I do not anymore remember all the discussion we have had related to fixed point devision, but you see immediately from the tests that logically these tests should compile and produce correct results. You possibly had different operator or syntax for this kind of division? I do not remember anymore.

Cheers, Heikki

**Comment by hbe72** [comment]
And now I found it... cnl::quotient. But what was the justification vs. / operator?

**Comment by hbe72** [comment]
Ok, I updated the branch with cnl::quotient(), and finally exposed my original bug. Try to compile CNL with -DCNL_INT128=OFF. The tie_to_inf datatype blows up ;)

**Comment by hbe72** [comment]
I added the floor_rounding_tag to this branch as well.

**Comment by johnmcfarlane** [comment]
Hi Heikki,

I don't see a pull request. Can you make one?

I see new code added for the tag, but also quite a few tests seem to be replaced entirely in test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point.cpp. The new tests cast to a new type and then assert that it's the new type. That is self-fulfilling. If the return type of the operator is wrong, these tests won't catch it. You should either not bother using `identical` or (preferably) not cast so that the return type -- as well as the value -- is tested.

> And now I found it... cnl::quotient. But what was the justification vs. / operator?

There are two mutually exclusive approaches to division as discussed in [P1368](http://wg21.link/p1368r1) and [P0037r7](wg21.link/p0037r7#Division-Operator):
1) to treat division the same way integer division works: lossless but with a remainder, or
2) to try and mimic floating-point arithmetic, i.e. 'quasi-exact'.

Because only one can be represented by operator/, the other is named `quotient`.

**Comment by hbe72** [comment]
I will do some changes and then do a pull request. I'm uncertain which should be the target branch? v1, v1.x or main? 

I actually moved the tie_to_pos_inf tests which were in test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point.cpp to 
test/unit/rounding/fixed_point/elastic_integer/elastic_fixed_point_tie_to_inf.cpp. I added that latter file. That is the reason for the change to look as replacement. Then I added some other tests.

The reason for using static_cast<T> is actually to test the convert operator. Regardless of the rounding mode, the multiplication itself for elastic_fixed_point produces exactly the same result, but the conversion is the one I try to test there. All things correct, static_cast<T> should call the correct conversion between datatypes if it finds a matching one. I perhaps should use the explicit conversion operator cnl::convert.

Division is not that straight forward, because result of division depends on the integer rounding mode.

Those multiplication and division tests, however, expose the unintendend feature. The datatype suddenly expands beyond maximum integer size. Maybe I got a little bit carried away. I will make a correction for separate conversion tests and separate multiplication tests.

**Comment by hbe72** [comment]
Now this should be in order.

Which branch should be the target branch for the pull order? Originally I started this on top of v1, but I will rename the branch and make proper pull request against desired target.

I found my INT128 problem:
It is very different to do:
```cpp
    namespace elastic_fixed_point_tie_to_pos_inf_multiply{
        static constexpr auto expected1 = T2{1.0};
        static constexpr T2 result1 = T2{2.0}*T2{0.5};
        static_assert(identical(expected1, result1), "test 1 multiply and round (elastic_fixed_point_tie_to_pos_inf)");
    }
```
than
```cpp
    namespace elastic_fixed_point_tie_to_pos_inf_multiply_2{
        static constexpr auto expected1 = T2{1.0};
        static constexpr T2 result1 = 2 * T2{0.5};
        static_assert(identical(expected1, result1), "test 1 multiply and round (elastic_fixed_point_tie_to_pos_inf)");
    }
```

The latter one blows datatype resulting from multiplication beyond 63 bits.

**Comment by johnmcfarlane** [comment]
There's no change yet. main is still the branch that shops be selected for
you by default. Once C++20 coffee is merged, you'll need to choose whether
you want to continue supporting older versions/compilers by merging to v1.x.

Are you sure there aren't two PRs here: fix to existing code + additional
tag? Haven't had time to look too closely yet. Happy to support out myself
if two PRs is more appropriate.

**Comment by hbe72** [comment]
I deduced that finally myself as well, thus I did PR against main.

On the PR count, you are probably correct. That T2 result1 = 2 * T2{0.5}; is a problem actually in cdsp code. Not in cnl.
Nevertheless, the additional tag is now introduced in add_neg_inf_rounding, branch, thus we can now close this discussion.
