### ISSUE TITLE
used_bits implementation for signed_multiprecision

### ISSUE THREAD

**Issue by hbe72** [johnmcfarlane/cnl#67]
This works:
` using q4_20 = cnl::fixed_point<unsigned_multiprecision<24>,-20>;`
`   q4_20 a = 3.051757812500000e-05;`
`  std::cout << "a  : " << a << " used_bits : " << used_bits(a) << " leading bits : " <<  leading_bits(a) <<  std::endl;'

Producing correctly:
`a  : 3.0517578125e-05 used_bits : 6 leading bits : 18`

This fails:
` using q4_20 = cnl::fixed_point<signed_multiprecision<24>,-20>;`
`  q4_20 a = 3.051757812500000e-05;`
`  std::cout << "a  : " << a << " used_bits : " << used_bits(a) << " leading bits : " <<  leading_bits(a) <<  std::endl;'

with:
`a  : 3.0517578125e-05 used_bits : unknown file: Failure`
`C++ exception with description "Division by zero." thrown in the test body.`
`Process finished with exit code 1`

**Comment by johnmcfarlane** [comment]
Fixed in #69. Sorry for the delay. Other things have gotten in the way of a lot of much-needed work in CNL recently.
