### ISSUE TITLE
.clang-format ?

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#671]
Transition to C++20 may be the last time in a while when adopting automatic formatting is timely.

Clang-Format still generates excessive changes due to the inflexibility of its indentation rules. However, they're about as good as they're going to get and I'm not convinced that alternatives won't involve swimming upstream.

Aside from the churn this will generate due to inconsistency within the codebase, there may be big changes that can really only be made now, or risk polluting the Git history excessively. 

In particular, is an indentation of 4 too great? With the typical verbosity that a template-based C++ library brings, there is a lot of white space in the left columns of the source code. A brief experiment with [an indentation of 2](https://gist.github.com/johnmcfarlane/242c86a8f677a17634b2db6427dd9a46#file-indent-of-2-cpp) looks better to me than with [an indentation of 4](https://gist.github.com/johnmcfarlane/242c86a8f677a17634b2db6427dd9a46#file-indent-of-4-cpp). Nested namespace declarations may help reduce blank area somewhat but isn't a formatting option so is less critical.

The main reason to avoid doing it normally is because it will pollute the git history, making tools such as `git blame` and `git show` and `git history` harder to use. The main reason to do it now is because the code is going to experience much churn anyway so pollution will be less prominent.

@hbe72 thoughts?

**Comment by hbe72** [comment]
@johnmcfarlane I agree that before starting the evolution towards concepts this is proper time to do this.

But I have no strong opinions on the formatting. I agree the indentation of 2 looks better, but in my opinion it is mainly due to continuation indentation of being 4, rather than basic indentation of being 2. The idea of indentation is to clearly show where the basic block starts, thus having it as 2, does not show that so well. 

How about having "basic" indent and continuation indent both as 4?

**Comment by johnmcfarlane** [comment]
@hbe72 the continuation indentation can start to be hard to distinguish from the regular indentation if they are the same. There's a good discussion of it [here in this talk](https://youtu.be/ZsHMHukIlJY?t=1260). Even when `{`s are on the next line, I find it hard to spot which is which straight away.

So I'm tempted not to change indentation at all. I might increase the page width from 100 to 120 though to compensate for all the space.

**Comment by johnmcfarlane** [comment]
Here's an example where I think that the template parameters of the class (ContinuationIndent) become hard to distinguish from the member function (IndentWidth) when they start at the same column:

of how I think it becomes less readable when continuation indent is the same as regular indent. Note how the 

[IndentWidth=4, ContinuationIndent=8](https://github.com/johnmcfarlane/cnl/blob/f066b5900142a0aa6729edeb7a5a2ef3996d03c1/include/cnl/_impl/duplex_integer/comparison.h#L23):
```c++
    template<typename Operator, typename Upper, typename Lower>
    struct comparison_operator<
            Operator, _impl::duplex_integer<Upper, Lower>, _impl::duplex_integer<Upper, Lower>> {
        CNL_NODISCARD constexpr auto operator()(
                _impl::duplex_integer<Upper, Lower> const& lhs,
                _impl::duplex_integer<Upper, Lower> const& rhs) const -> bool
        {
            using tuple = std::tuple<Upper const&, Lower const&>;
            return Operator{}(tuple(lhs.upper(), lhs.lower()), tuple(rhs.upper(), rhs.lower()));
        }
    };
```

[IndentWidth=4, ContinuationIndent=4](https://github.com/johnmcfarlane/cnl/blob/dd07fbb1c89ec87aa91f357b52051d6eafd81aa8/include/cnl/_impl/duplex_integer/comparison.h#L23):
```c++
    template<typename Operator, typename Upper, typename Lower>
    struct comparison_operator<
        Operator, _impl::duplex_integer<Upper, Lower>, _impl::duplex_integer<Upper, Lower>> {
        CNL_NODISCARD constexpr auto operator()(
            _impl::duplex_integer<Upper, Lower> const& lhs,
            _impl::duplex_integer<Upper, Lower> const& rhs) const -> bool
        {
            using tuple = std::tuple<Upper const&, Lower const&>;
            return Operator{}(tuple(lhs.upper(), lhs.lower()), tuple(rhs.upper(), rhs.lower()));
        }
    };
```

[IndentWidth=2, ContinuationIndent=4](https://github.com/johnmcfarlane/cnl/blob/6a19510636e7c5b7ae4557fdb1f1c34d0076d18d/include/cnl/_impl/duplex_integer/comparison.h#L23):
```c++
  template<typename Operator, typename Upper, typename Lower>
  struct comparison_operator<
      Operator, _impl::duplex_integer<Upper, Lower>, _impl::duplex_integer<Upper, Lower>> {
    CNL_NODISCARD constexpr auto operator()(
        _impl::duplex_integer<Upper, Lower> const& lhs,
        _impl::duplex_integer<Upper, Lower> const& rhs) const -> bool
    {
      using tuple = std::tuple<Upper const&, Lower const&>;
      return Operator{}(tuple(lhs.upper(), lhs.lower()), tuple(rhs.upper(), rhs.lower()));
    }
  };
```

**Comment by hbe72** [comment]
(4,4) looks visually the least busy but may not deliver the clarity. The indent width 2 looks too crowded for me. It does not convey enough visual cues. This is difficult. I really do not have strong opinions. I can live with all of them.
