### ISSUE TITLE
Documentation missing math functions

### ISSUE THREAD

**Issue by DragonJawad** [johnmcfarlane/cnl#697]
Apologies if this is listed somewhere and I keep missing it, but I've been going through the documentation page by page and I can't seem to find the cnl::sqrt function mentioned anywhere (which I realized existed while watching that excellent CppCon 2017 presentation). In addition, on pages listing available functions like the one mentioned below, the abs function doesn't seem to be listed there as well:
https://johnmcfarlane.github.io/cnl/namespacemembers_func.html

In addition, I believe there was some mention of in-progress trig functions in the CppCon 2017 presentation as well, but issue #341 seems to imply those functions aren't available as well.

There's a good chance I'm simply missing these functions in the documentation (such as overly relying on the [function listing pages](https://github.com/johnmcfarlane/cnl/issues/341)), but thought it may be helpful to write this issue just in case.

------

As a side note, is there any thorough all-in-one place documentation on rounding capabilities and intentions? Having a bit of trouble piecing together the current supported behavior and options (eg, if it's possible to keep a more consistent size esp with respect to exponents at the cost of [decimal] precision when multiplying and dividing)

**Comment by johnmcfarlane** [comment]
All of the definitions in [_include/cnl/_impl/scaled_integer/extras.h_](https://github.com/johnmcfarlane/cnl/blob/v1.1.3/include/cnl/_impl/scaled_integer/extras.h) were excluded from the docs due to problems Doxygen had with processing that file. It's no longer excluded and `sqrt` and `abs` from that file are showing up in docs.

Within the same file are a few trig functions, however, that are placeholders; they call floating-point functions. They should be usable but I'm hesitant to document something that falls back on FPU support. I do still want to implement such functions in the future but as pointed out in #341, it's not trivial to implement lookup tables without `constexpr` support in <cmath>.

Are you looking for a simple equivalent to the existing standard functions such as `std::cos` or are lookup tables more useful to you? I'd be curious to know roughly what HW/application/toolchain you have in mind (if any). Thanks.

No, rounding isn't especially well documented. Take a look at `rounding_integer` and the classes ending with `_rounding_tag` for details of the different rounding modes.

**Action**: pad out the Doxygen entry for `cnl::rounding_integer` and include `/sa` commands for the rounding tags/concept.

**Comment by DragonJawad** [comment]
Thank you for looking into this, I really appreciate the response and it's nice to know those are all in extras.h as well

As for my needs, I think they may be a bit unique compared to other CNL users. I'm attempting to build a deterministic multiplayer game (with Unreal but building out a separate pure C++ simulation layer including a standalone simple physics engine). World units are essentially in cm, so "decimal" accuracy (not sure for the term for numbers beyond the decimal point) isn't too important but accurate replication across all hardware (cross-platform across PCs and consoles at least) is more important to me.

Essentially, my project more so relies on deterministic behavior while pinpoint accuracy isn't that important (as it shouldn't be noticeable in gameplay). Thus, a lookup table would definitely serve my needs pretty well.

------------------------------

As for a quick question on top- has there been any consideration for recreating floating point-like behavior with CNL, where loss of precision is acceptable while preventing overflows and type size escalations? I actually temporarily reverted back to floats in my project as ran into various odd issues with scaled_integers via CNL v1.x (constantly tweaking power/exponent and size of a `scaled_integer` and `elastic_scaled_integer` but finally temporarily gave up once multiplying several fixed point numbers in a row led to a 0 being consistently outputted- suspecting overflow issue without overflow exceptions being thrown)

Worried that my use case may in fact be outside the scope of CNL. However, I'll look into the `rounding_integer` which may be what I'm looking for, thank you!

**Comment by johnmcfarlane** [comment]
Floating-point is actually very effective at "preventing overflows and type size escalations". Knowing the exponent of a value at run-time is a huge advantage which fixed-point must work around.

But losing precision isn't a problem. Simply cast back to the original type with the greater exponent value and less significant bits will be dropped. Your number may end up being flushed when this happens: all significant bits are lost and the value is zero. Again, not a serious problem with floating-point.

[Example](https://godbolt.org/z/66cx6q):

```c++
using fp = scaled_integer<elastic_integer<8>, power<-4>>;

// 1/8 stored with 4 fractional digits
auto input = fp{0.125};
print("input={}\n", input);

// 1/64 stored with 8 fractional digits
auto square = input*input;
print("square={}\n", square);

// approximation of 1/64 stored with 4 fractional digits is 0!
auto truncated = fp{square};
print("truncated={}\n", truncated);
```

**Comment by DragonJawad** [comment]
Ahhh yup, I've been definitely running into the truncation issue (as I explicitly define the same type every time - eg "fp" here - instead of using auto). I need to work on my numerical supported range a bit more, as I definitely need 64 bits to, say, support whole numbers of [-10 million, 10 million] and "decimal" numbers of around [0, 10000].

However, I do remember there being some odd issue with trying to use a `int64_t` type for the scaled_integer, eg `scaled_integer<uint64_t, power<-24>`. If I understand the documentation and examples correctly, that should be 24 bits for fractional/decimal piece, 1 bit for sign, and (64-24-1)=39 bits for the non-fractional piece. However, I ran into issues when trying to do a vector normalize operation (multiply -> adding -> sqrt -> divison) and perhaps other similar operations, with compilation errors similar to the following:
```
...
2>FixedPointTests.cpp
2>FixedPointVectorTests.cpp
2>C:\Program Files (x86)\cnl\include\cnl\_impl\num_traits\set_digits.h(92,128): error C2504: 'cnl::signed_integer_cannot_have<127>::digits_because_maximum_is<63>': base class undefined
2>C:\Program Files (x86)\cnl\include\cnl\_impl\num_traits\set_digits.h(152): message : see reference to class template instantiation 'cnl::_impl::set_digits_signed<127,void>' being compiled
2>C:\Program Files (x86)\cnl\include\cnl\_impl\num_traits\set_width.h(19): message : see reference to class template instantiation 'cnl::set_digits<T,127,void>' being compiled
2>        with
2>        [
2>            T=__int64
2>        ]
2>C:\Program Files (x86)\cnl\include\cnl\_impl\scaled_integer\extras.h(81): message : see reference to class template instantiation 'cnl::_impl::set_width<Rep,128>' being compiled
2>        with
2>        [
2>            Rep=__int64
2>        ]
2>C:\Program Files (x86)\cnl\include\cnl\_impl\scaled_integer\extras.h(81): message : see reference to alias template instantiation 'cnl::_impl::set_width_t<__int64,128>' being compiled
2>C:\Program Files (x86)\cnl\include\cnl\_impl\scaled_integer\extras.h(113): message : see reference to function template instantiation 'Rep cnl::_impl::sqrt_solve1<-24>::operator ()<Number>(Rep) const' being compiled
2>        with
2>        [
2>            Rep=__int64,
2>            Number=__int64
2>        ]
...
```

I'm pretty certain I have to use an `int64_t` to assure I have the correct range (+/- 10 million with 0-10k fractional) but it seems that this runs into a hard limitation related to the type size escalation (apologies if I'm misremembering the term there).

Is there some way for me to get around this limitation? Or is my numerical range outside the scope of CNL?


Also apologies for sidetracking this issue further. I've been trying to go up and down the documentation + examples trying to figure out how to use CNL for my exact use case (specific numerical range with emphasis on utilizing determinism of integers without too much of a care for precision), and I think this may be the last piece I've been failing to understand to fully utilize the library.

**Comment by johnmcfarlane** [comment]
Unfortunately yes, sqrt currently uses an intermediate value which is twice
as wide as the operand. So on MSVC (for which 64-bit integers is the
limit), you must use 32-bit (or narrower) operands. Additionally, there are
other faults with the API of sqrt which make it relatively low-quality. It
is in the backlog though under #341. And I've added #712 to make this
design goal explicit.

In general, while low bits are valuable, it's far more important to avoid
high bits being lost. The former results in precision loss but the latter
results in UB or entirely incorrect results.

So when choosing on an individual type, decide what storage you can afford
(in this case 32-bit if you want to continue using cnl::sqrt but 64-bit
otherwise), then chose a maximum magnitude which you will never exceed
(unless you have a bug), and then allocate all remaining bits to fractions.
If one single range&resolution is not adequate for all your needs, make
more and convert between them when necessary. 24 bits is an entirely
arbitrary choice. If you want to get down to centimeter precision, then you
just need a decimal fixed-point number with 2 fractional digits:

    scaled_integer<int32_t, power<-2, 10>>  // range = (21,474,836.48,
-21,474,836.48], resolution = 0.01

**Comment by DragonJawad** [comment]
Thank you for the in depth explanation! Unfortunately I'm afraid a fractional range of [-0.48, 0.48] would be far too small, especially when working with rotations (eg, when using radians to calculate multiple rotations at once which would then be used for further calculations immediately after).

However, as it seems like it'll be impossible to go with my intended range with CNL as is due to outside limitations, I'm sure I'll be able to find a workaround such as using two int32_t scaled_integers or some finagling with the world units (eg, break the world into smaller chunks with simple relative units to assure a smaller max numerical range is used with no real harm to upstream systems and experience).

Overall, just want to say truly thank you- both for creating CNL as well as for all the help here! I had somewhat given up on using CNL until months later down the line for another attempt, but this conversation made me far more confident to go back and start using it again.

-------------------------------

As a side note, on topic of documentation, I can't seem to find anything specific on `cnl::power`, especially when the two parameter version would be preferred. Code does mention exponent and radix, but I'm surprised the docs don't go more in depth on such an often used tool. (And I also learned how it worked in terms of bit allocation by looking at one of the commented examples on the intro doc page)

**Comment by johnmcfarlane** [comment]
Do you think you could achieve your goals with raw integer arithmetic alone?

**Comment by DragonJawad** [comment]
Depends on what you're referring to as "raw", but if referring to relying on just integers rather than floating points at all, then I'd say almost definitely yes. Fortunately I can confidently maintain a numerical range, and regarding dealing with "worlds" larger than the intended range, that's something modern game engines/developers deal with when using floating point already at very large position values. The real concerns are more so centered around overall efficiency as well as accuracy of smaller fractional numbers when relevant (eg, anything somewhat trig related).

For instance, a technique previously used for cross-platform determinism in games has been a two integer fixed point type something akin to a fixed_point<int32_t, int32_t>, where two separate integers are used for the non-fractional and fractional pieces respectively. I haven't tested it out myself personally but I'd assume it'd be slower than using CNL, which seems to be optimized far better than the pretty straightforward code I've seen before. However, either way I can't seem to find a significant obstacle that would prevent using pure integer arithmetic (other than time but that's always a fun limitation).

I may be proven wrong a while down the line, but for the moment I'm fairly confident in integer arithmetic =)

**Comment by johnmcfarlane** [comment]
The improvements to `cnl::sqrt` are completed. It no longer uses a wider intermediate integer type. 
Capturing doc improvements in #753. An FAQ section was added to the front page with some examples. More to follow.
Closing this now as there are quite a few points raised in this issue and most of them are now captured elsewhere. If anything is outstanding, feel free to open individual issues.
Thanks

**Comment by johnmcfarlane** [comment]
`rounding_integer` and `overflow_integer` and their tags are now documented. Division is [explained](https://johnmcfarlane.github.io/cnl/index.html#division) in the FAQ. LMK if I missed anything. Math functions yet to come...
