### ISSUE TITLE
Multiplying 2 numbers with different sizes

### ISSUE THREAD

**Issue by priyankaankolekar** [johnmcfarlane/cnl#714]
I am trying to multiply 2 numbers as shown below:
cnl::fixed_point<std::uint32_t, -16> a = 0xb4000000   //46080
cnl::fixed_point<std::uint16_t, -16> b = 0x67                 //0.0015716552734375

cnl::fixed_point<std::uint64_t, -32> c = a * b                // expected = 72.421875, 0x486c000000

Instead I get:
0x6c000000 (0.421875)

I cannot figure out why the integral part is getting truncated. There seem to be enough number of bits in the result variable to hold the final result.

**Comment by hbe72** [comment]
a is integer with 16 bit integer part and 16 bit fractional part.
b is integer with 0 bit integer part and 16 bit fractional part
Obviously the multiplication should produce a number which has 16 bit integer part and 32 bit fractional part. 

However that type does not do promotion of the base integer type automatically. The resulting type from that multiplication is still cnl::fixed_point<std::uint32_t, -32>, it does not help anymore to assign that to wider cnl::fixed_point<std::uint64_t, -32>  as the precision was lost in multiplication.

Please use elastic fixed point (or elastic number) instead, which use elastic integer as the base type. Then CNL machinery will deduce that 32 bit is not sufficient to hold the result of that multiplication and the base type of the multiplication is "widened" to 64-bits and no precision is lost.

**Comment by priyankaankolekar** [comment]
Got it. Thanks.

Another issue I see is with division by an integer. It seems to round even if there are sufficient bits to represent the outcome.
Something like (a/4) or (a/5) where 'a' is a fixed_point number. In this case does the library expect the integer to be cast to the same type as 'a'?

**Comment by hbe72** [comment]
John explained this to me not too long ago:

" There are two mutually exclusive approaches to division [P1368](http://wg21.link/p1368r1) and [P0037r7](https://github.com/johnmcfarlane/cnl/issues/wg21.link/p0037r7#Division-Operator)

to treat division the same way integer division works: lossless but with a remainder, or
to try and mimic floating-point arithmetic, i.e. 'quasi-exact'.

Because only one can be represented by operator/, the other is named quotient"

Thus try cnl::quotient(a, b)

**Comment by johnmcfarlane** [comment]
Attempt at answering first question is in #727.

**Comment by johnmcfarlane** [comment]
Second question captured in #753.

**Comment by johnmcfarlane** [comment]
Quasi-exact arithmetic planned in #788

**Comment by johnmcfarlane** [comment]
Division [explained](https://johnmcfarlane.github.io/cnl/index.html#division) in the FAQ now.
