### ISSUE TITLE
Building from source doesnt work.

### ISSUE THREAD

**Issue by ValorZard** [johnmcfarlane/cnl#820]
I get this strange error
C:\Users\sraya\OneDrive\Documents\GitHub\cnl>mkdir build && cd build

C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build>cmake ..
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at test/CMakeLists.txt:29 (find_package):
  By not providing "Findbenchmark.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "benchmark", but CMake did not find one.

  Could not find a package configuration file provided by "benchmark" with
  any of the following names:

    benchmarkConfig.cmake
    benchmark-config.cmake

  Add the installation prefix of "benchmark" to CMAKE_PREFIX_PATH or set
  "benchmark_DIR" to a directory containing one of the above files.  If
  "benchmark" provides a separate development package or SDK, be sure it has
  been installed.

-- Google Benchmark is required to build test-benchmark.
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Google Test is required to build unit tests.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/sraya/OneDrive/Documents/GitHub/cnl/build

C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build>cmake --build . --target install
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/sraya/OneDrive/Documents/GitHub/cnl/CMakeLists.txt
  -- Install configuration: "Debug"
  -- Installing: C:/Program Files (x86)/cnl/include
  CMake Error at cmake_install.cmake:36 (file):
    file INSTALL cannot make directory "C:/Program Files (x86)/cnl/include": No
    such file or directory.

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: The command "setlocal [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: "C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Debug -P cmake_install.cmake [C:\Users\s
raya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxp
roj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :cmEnd [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\Users\sraya\OneDrive\Documents\GitHu
b\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :cmErrorLevel [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: exit /b %1 [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :cmDone [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxp
roj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :VCEnd" exited with code 1. [C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build\install.vcxproj]

C:\Users\sraya\OneDrive\Documents\GitHub\cnl\build>

**Comment by johnmcfarlane** [comment]
Hi. A few questions:
* Are you trying to run tests or just use the library?
* Which version are you running: _main_, _v1.x_ or something else?
* Are you following the instructions from the README?
Thanks

**Comment by hbe72** [comment]
Hi @johnmcfarlane and @ValorZard 

This is one of the symptoms of README.md of not being absolutely up to date and was discussed in [Pull Request #802](https://github.com/johnmcfarlane/cnl/pull/802). You are seeing this because 1) dependencies are not in place and 2) cmake module file path is not set (or alternatively Conan does not use cmake_paths generator).

If you look at the CMakeLists.txt cmake goes to test subdirectory in all cases and looks for the dependencies even though you are asking only install step and not compilation of tests-all. 

You should be able to compile fully with conan approximately along these lines:
```bash
%  mkdir build; cd build
% conan profile new --detect --force default
%  conan profile update settings.compiler.libcxx=libstdc++11 default
%  conan install --build=missing --env CONAN_CMAKE_TOOLCHAIN_FILE="$(pwd)"/../test/toolchain/msvc.cmake \
     --options target=test-all --options test_pattern="^test-unit-" ..
% conan build --configure --build ..
% conan build --test ..
% cmake --build . --target install
```
or with cmake after using conan to get the dependencies
```bash
% mkdir build; cd build;
% conan profile new --detect --force default
% conan profile update settings.compiler.libcxx=libstdc++11 default
% conan install --build=missing 
% cmake -DCMAKE_MODULE_PATH:FILEPATH="$(pwd)" \ 
    -DCNL_GTEST_MAIN_TARGET:STRING=GTest::gtest_main \ 
    -DCMAKE_TOOLCHAIN_FILE="$(pwd)"/../test/toolchain/msvc.cmake \ 
% cmake --build . --target test-all
% cmake --build . --target install
```

As the pipeline builds are working a good place to start looking for solution is the source code of pipeline: [.github/workflows](https://github.com/johnmcfarlane/cnl/tree/main/.github/workflows)

**Comment by johnmcfarlane** [comment]
@hbe72 I'm not certain that @ValorZard is trying to build or run tests as they are following the instructions for building and installing the library, not the instructions for building and running the tests.

@ValorZard I don't know how/whether it's possible to install a library to the system on Windows using CMake. However, it may help if you're administrator. Alternatively, if you want to install a CMake-built project to a user directory, using the [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) flag may help:

```shell
cmake CMAKE_INSTALL_PREFIX=C:/Users/sraya/ ..
```

**Comment by ValorZard** [comment]
Niether running tests or building the library worked for me, sadly. Fortunately, I was able to find this library that basically did everything I wanted anyways: https://github.com/MikeLankamp/fpm

**Comment by johnmcfarlane** [comment]
The library is header only; there is nothing to build. So not much more than including <cnl/all.h> should be necessary.

Anyway, thanks for the feedback. I'm working on [new instructions](https://github.com/johnmcfarlane/cnl/pull/828/commits/e45f55c3a026074f973a719ed6b2e750b68887c7?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and [a better bug reporting template](https://github.com/johnmcfarlane/cnl/compare/issue-templates).
