### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by nicholasbishop** [johnmcfarlane/cnl#87]
The documentation link in the README currently points to http://johnmcfarlane.github.io/cnl/, which 404s.

**Comment by johnmcfarlane** [comment]
For the time being, please refer to the documentation [here](http://johnmcfarlane.github.io/fixed_point/). It is mostly still accurate with the main exception that the namespace `sg14` has been changed to `cnl`.

**Comment by johnmcfarlane** [comment]
The link now works. Not all the API is adequately documented. Please LMK if there is a specific class or function that you'd like to see improved as a priority. Thanks
