### ISSUE TITLE
sqrt(4) is ambiguous

### ISSUE THREAD

**Issue by johnmcfarlane** [johnmcfarlane/cnl#890]
https://godbolt.org/z/s57Tqba8o

**Comment by dnmiller** [comment]
I hit this today on `v2.0.0-development`. Any plans on tagging a new prerelease soon?

**Comment by johnmcfarlane** [comment]
@dnmiller frankly, that tag isn't much better than _main_. It's occasionally keeping up with what is in _main_, I'm a long way from stabilising the API (It *will* change significantly before is settles down) and there's no special testing or bug-fixing going into the tag. If you're happy to use -v2.0.x-development_ then _main_ -- or whatever SHA it points to today -- should be just as good.

However, I just pushed a v2.0.1-development and it seemed to work. Do you want to try that out?

**Comment by dnmiller** [comment]
That worked. Thanks!
