### ISSUE TITLE
Confused by some behavior...

### ISSUE THREAD

**Issue by bongodrum** [johnmcfarlane/cnl#896]
Hi John,

I'm pretty new to fixed-point math, but CNL looks like a really nice library and I've been trying to get my head around how to use it. I'm looking for something to replace 'float' for determinism reasons.

In my experimenting so far, there's a couple of things that have puzzled me, and I thought maybe you could tell me what's going on. I'm using [Version 1.x](https://github.com/johnmcfarlane/cnl/tree/v1.x) (I'm limited to C++ 11) and Visual Studio 16.10.0.

First, this code:
```
using mytype = cnl::scaled_integer<>;
auto n = mytype { 1 };
std::cout << "sizeof: " << sizeof(mytype) << std::endl;
std::cout << "min: " << std::numeric_limits<mytype>::min() << std::endl;
std::cout << "lowest: " << std::numeric_limits<int>::lowest() << std::endl;
std::cout << "lowest: " << std::numeric_limits<mytype>::lowest() << std::endl;
std::cout << "max: " << std::numeric_limits<mytype>::max() << std::endl;
std::cout << "value: " << n << std::endl;
```
Gives this output:
```
sizeof: 4
min: 1
lowest: -2147483648
lowest: -./,),(-*,(
max: 2147483647
value: 1
```
The 'lowest' value for the scaled_integer does not display correctly. I imagine this may just be a bug, possibly fixed in V2, but thought I'd check.

Second, this code works great:
```
using mytype = cnl::static_number<31, -16>;
auto n = mytype{ 150.12345 };
std::cout << "sizeof: " << sizeof(mytype) << std::endl;
std::cout << "min: " << std::numeric_limits<mytype>::min() << std::endl;
std::cout << "lowest: " << std::numeric_limits<mytype>::lowest() << std::endl;
std::cout << "max: " << std::numeric_limits<mytype>::max() << std::endl;
std::cout << "value: " << n << std::endl;
```
```
sizeof: 4
min: 0.0000152587890625
lowest: -32767.9999847412109375
max: 32767.9999847412109375
value: 150.123443603515625
```

As does this:
```
using mytype = cnl::static_number<63, -32>;
auto n = mytype{ 150.12345 };
std::cout << "sizeof: " << sizeof(mytype) << std::endl;
std::cout << "min: " << std::numeric_limits<mytype>::min() << std::endl;
std::cout << "lowest: " << std::numeric_limits<mytype>::lowest() << std::endl;
std::cout << "max: " << std::numeric_limits<mytype>::max() << std::endl;
std::cout << "value: " << n << std::endl;
```
```
sizeof: 8
min: 0.00000000023283064365386962890625
lowest: -2147483647.99999999976716935634613037109375
max: 2147483647.99999999976716935634613037109375
value: 150.12345000007189810276031494140625
```

But I don't understand what's going on here. If I change the value to 1, I get a "positive overflow" exception.
```
using mytype = cnl::static_number<63, -32>;
auto n = mytype{ 1 };
std::cout << "sizeof: " << sizeof(mytype) << std::endl;
std::cout << "min: " << std::numeric_limits<mytype>::min() << std::endl;
std::cout << "lowest: " << std::numeric_limits<mytype>::lowest() << std::endl;
std::cout << "max: " << std::numeric_limits<mytype>::max() << std::endl;
std::cout << "value: " << n << std::endl;
```
However, if I change it to "1.0f", it works fine:
```
using mytype = cnl::static_number<63, -32>;
auto n = mytype{ 1.0f };
std::cout << "sizeof: " << sizeof(mytype) << std::endl;
std::cout << "min: " << std::numeric_limits<mytype>::min() << std::endl;
std::cout << "lowest: " << std::numeric_limits<mytype>::lowest() << std::endl;
std::cout << "max: " << std::numeric_limits<mytype>::max() << std::endl;
std::cout << "value: " << n << std::endl;
```
```
sizeof: 8
min: 0.00000000023283064365386962890625
lowest: -2147483647.99999999976716935634613037109375
max: 2147483647.99999999976716935634613037109375
value: 1
```
Any advice you can give is much appreciated, thanks!

Andy

**Comment by johnmcfarlane** [comment]
Hi Andy,

Thanks for checking out CNL and getting in touch. 

> The 'lowest' value for the scaled_integer does not display correctly. I imagine this may just be a bug, possibly fixed in V2, but thought I'd check.

Yes, the major formatting problems are fixed in the _main_ branch: https://godbolt.org/z/dor776vT1

> But I don't understand what's going on here. If I change the value to 1, I get a "positive overflow" exception.

`scaled_integer` literally just scales the value internally using a multiply operation. `1` is an `int` so in this case, the member variable is initialised with expression, `1 * (1<<32)`, which overflows. Use `1LL` or `INT64_C(1)` instead: https://godbolt.org/z/3hW16ebEn

John

**Comment by bongodrum** [comment]
> the member variable is initialised with expression, 1 * (1<<32), which overflows

Ah I see, it's being shifted as an int _before_ hitting the 8 byte internal storage... makes sense. Out of curiosity, what happens when I use 1.0f? I imagine that's a more complex initialization to preserve the fractional part.

I'm thinking cnl::static_number<31, -14> may be suitable for my purposes... as a general float replacement. Does that seem reasonable to you?

**Comment by johnmcfarlane** [comment]
> Out of curiosity, what happens when I use 1.0f? I imagine that's a more complex initialization to preserve the fractional part.

Floating-point actually deals with expressions like `1.f * (1<<32)` more easily than integers. IOW, it doesn't try and do anything 'clever' with the bits inside a float.

> I'm thinking cnl::static_number<31, -14> may be suitable for my purposes... as a general float replacement. Does that seem reasonable to you?

I wouldn't say it's a *general* replacement. But depending on your needs it can be a very powerful abstraction. I made a list of pros and cons [here](https://stackoverflow.com/a/67309499/671509).

Note that division is handled differently. (See [this FAQ section](https://johnmcfarlane.github.io/cnl/index.html#division) for explanation.) I have plans to offer a division operator that's more like a floating-point division.

**Comment by bongodrum** [comment]
Thanks John, that all makes sense. It's working nicely so far, thanks for your help.

**Comment by johnmcfarlane** [comment]
You're welcome. Sounds like questions are answered so closing now.
