### ISSUE TITLE
Formatting within GDB

### ISSUE THREAD

**Issue by dzarda** [johnmcfarlane/cnl#903]
**What is your question?**

Do we have a straightforward way for printing the value within a debugger? There's to_chars but I'm not sure how to use it in this context.

**What environment are you working in?**

ARM Cortex M0, GCC/GDB, CNL 1.x

**Comment by johnmcfarlane** [comment]
I'm not sure quite what you're trying to do. (I understanf there's a Python-based scripting system in GDB.) But you may find `cnl::to_chars_static` helpful. It returns a number-to-test conversion as a fixed-size array, e.g.:

```
using num = cnl::scaled_integer<std::int64_t, cnl::power<-60>>;
constexpr auto pi = std::numbers::pi_v<num>;
constexpr auto num_text = cnl::to_chars_static(pi);
std::puts(num_text.chars.data());
```

It's (hopefully) not documented and not a stable API but works for now. There's also `cnl::to_string`:

```c++
std::puts(cnl::to_string(pi).c_str());
```

([Compiler Explorer](https://godbolt.org/z/jPa5zaq5E))

**Comment by dzarda** [comment]
Thanks for the pointers. I'm inspecting variables while debugging, and the default GDB formatting is as follows:

```
print vbus
$1 = {<cnl::_impl::number<long, cnl::power<-8, 2> >> = {_rep = 2355}, <No data fields>}
```

AFAIK the Python support is not compiled in for the release I have available. Should investigate.
