### ISSUE TITLE
to_rep doesn't work with namespace cnl prepended

### ISSUE THREAD

**Issue by dnmiller** [johnmcfarlane/cnl#908]
**Describe the bug:**
I've discovered some unexpected behavior in to_rep. The following program will compile:

    #include <cnl/all.h>
    #include <iostream>
    int main()
    {
        auto x = cnl::scaled_integer<std::int16_t, cnl::power<-1>>{3.5};
        std::cout << to_rep(x) << "\n";
    }

But putting `cnl::` in front of `to_rep` breaks things

    #include <cnl/all.h>
    #include <iostream>
    int main()
    {
        auto x = cnl::scaled_integer<std::int16_t, cnl::power<-1>>{3.5};
        std::cout << cnl::to_rep(x) << "\n";
    }

with an error like

    <source>: In function 'int main()':
    <source>:7:31: error: class template argument deduction failed:
        7 |     std::cout << cnl::to_rep(x) << "\n";

This happens with both GCC 10.3 and LLVM 12.

**Expected behavior:**

It should build.

**Desktop (please complete the following information):**

* OS: Ubuntu 20.04
* Compiler version: GCC 10.3 or LLVM 12 (also on godbolt)
* Compiler flags used: -std=c++20
* CMake version NA
* Conan version NA
* CNL version (or Git branch/SHA) main

**Link to Compiler Explorer:**
Broken version:
https://godbolt.org/z/Pjahq8fP1

Fixed version:
https://godbolt.org/z/o3M8o5bMd

**Comment by johnmcfarlane** [comment]
Confusingly, the unqualified call is resolving to totally different symbol, a function in another namespace, `cnl::_impl::to_rep`. This is tracked in #656.

It's ugly but you can type:

```c++
    std::cout << cnl::to_rep<cnl::scaled_integer<std::int16_t, cnl::power<-1>>>{}(x) << "\n";
```

or:

```c++
    std::cout << cnl::to_rep<decltype(x)>{}(x) << "\n";
```

Does the current situation block you or is it simply surprising/annoying.

**Comment by dnmiller** [comment]
Sorry didn't see the other issue. I probably didn't remove the "is:open" filter that's on by default.

It's not blocking, just weird and unexpected.

**Comment by johnmcfarlane** [comment]
Closing as this is tracked elsewhere. Thanks for the feedback!
