### ISSUE TITLE
is_scaled_tag returns false for scaled_integer

### ISSUE THREAD

**Issue by dnmiller** [johnmcfarlane/cnl#909]
**Describe the bug:**

Sorry if I'm diving into undocumented/unstable territory, but I thought this was worth reporting.

I was trying to create some traits/concepts for CNL types to branch code when a CNL type is given vs. a plain old integer or something else, and discovered is_scaled_tag in the source code. Unfortunately, it always seems to report false, even when given a scaled integer.

**To Reproduce:**

Example here: https://godbolt.org/z/5hdr8ETeK

**Expected behavior:**

Output of code to be true.

**Additional context:**

If this is considered not a bug because it's undocumented, then please consider it as a feature request.

**Update**: After digging round more, I realize this was meant for the tag object, not scaled integer, so it is not a bug. Please consider it a feature request then. Thanks.

**Comment by johnmcfarlane** [comment]
Are you suggesting a new trait, `is_scaled_integer`? You could write one quite easily. https://godbolt.org/z/xdh8s7jEr

```c++
template<typename T>
struct is_scaled_integer : std::false_type {};
template<integer Rep, typename Tag>
struct is_scaled_integer<scaled_integer<Rep, Tag>> : std::true_type {};
```

I'm curious to know: in what significant way would `scaled_integer<int, S>` differ from `int` in your code branch?

**Comment by dnmiller** [comment]
You're correct, it was very easy to write my own.

It's actually not differing from int that I'm doing, it's differing from [this](https://github.com/Xilinx/HLS_arbitrary_Precision_Types). I'm trying to write some generic code that can move between FPGA and MCU implementations.

**Comment by johnmcfarlane** [comment]
There is a `fixed_point` concept which may be of use to you. It allows `scaled_integer` and all kinds of integers. It excludes fractions and floating-point types.

**Comment by dnmiller** [comment]
The `fixed_point` concept is what I'm looking for. Thanks! I'll close this issue.
