### ISSUE TITLE
Publishing CNL 1.x libraries to platformio

### ISSUE THREAD

**Issue by henrygab** [johnmcfarlane/cnl#915]
**What would you like to see in CNL?**

I would like CNL v1.x (and optionally 2.x) to registered releases with PlatformIO, to make it trivial for projects to reference, download, and use this amazing library (specifically, in projects targeting IoT class processors, where the lack of a hardware FPU makes it even more valuable).

**What are you trying to do?**

A project had a recent PR that added a ton of floating-point math to a performance-sensitive code path.  The processors either don't have a hardware FPU, or one that's only partial (e.g., no division).  So, I wanted to convert it to use only integer maths.

CNL was great!  I used CNL's `scaled_integer` to convert these routines to use fixed-point math.  

I then [searched](https://platformio.org/lib/search?query=header%253Aall.h&page=1) in platformio for this library ... and came up empty.  It appears that CNL is not registered with platformio.  This makes adding the headers to projects much more difficult than most libraries supported by platformio.

**What environment are you working in?**

OS: Windows 10
IDE: Visual Studio Code + PlatformIO extension
Specific Project: [WLED](http://github.com/Aircookie/WLED)

**What, if any, instructions are you following?**

I considered just publishing a version myself.  However, that would cause pain and confusion if/when you opted to publish an official drop of the library.

It's really easy to publish the library:
1. Install platformio (temporarily or in a VM is OK)
2. Create a manifest file, [`library.json`](https://docs.platformio.org/en/latest/librarymanager/config.html#library-json)
3. Validate the manifest file with [`pio package pack`](https://docs.platformio.org/en/latest/core/userguide/package/cmd_pack.html#cmd-package-pack)
4. Use [`pio package publish`](https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html#cmd-package-publish) to publish the library

NOTE: I'm happy to generate a draft version of the manifest file, upon request.

Recommended library names:
* `cnl_cpp11` for the 1.x branch releases (critical for IoT ... where C++11 is the norm, if C++ is used at all)
* `cnl_cpp20` for the 2.x branch releases (avoid "upgrades" from C++11 version to C++20 version)

Interested?

**Comment by johnmcfarlane** [comment]
Hi Henry. Thanks for getting in touch and I'm glad to hear that you found CNL useful. 

Addition of a PlatformIO manifest file was requested in #805. I was keen to explore a non-intrusive solution for reasons given there. This resulted in [platformio/platformio-core/issues/3887](https://github.com/platformio/platformio-core/issues/3887) which remains open and CNL was [forked](https://github.com/maxgerhardt/cnl) as you suggest. I'm not sure why that fork doesn't show up in your search or how actively it is maintained, but if you wanted to publish your own fork, you'd be more than welcome.

I'm still hesitant to add orthogonal package system files to the upstream for the same reasons given before. Perhaps you could weigh in on the issues mentioned [here](https://github.com/platformio/platformio-core/issues/3887#issuecomment-803609521) which seem to prevent seamless use of packages in PlatformIO.

**Comment by henrygab** [comment]
@johnmcfarlane , thanks for the quick response, and pointer to the prior issue.  I don't know why it didn't appear in my search (I _did_ search issues first!).  As for fork not appearing, that's because the library doesn't appear to be registered with PlatformIO.  Instead, their solution is to include the library by specifying the git repo and tag directly, which PlatformIO supports:

`lib_deps = https://github.com/maxgerhardt/cnl.git#v1.1.7-pio`

Unfortunately, this means people searching for CNL with PlatformIO won't find that it's available for use, since only registered libraries can be searched.

Still... I greatly appreciate your responsiveness, and helping unblock me.  👍

**Comment by ivankravets** [comment]
Hi @johnmcfarlane, 

Founder of PlatformIO here. There is no requirement to add `library.json` to the source code repository. You can copy a source code of `v1.1.2` to some folder on your local machine, add `library.json`,  and [publish](https://docs.platformio.org/en/latest/librarymanager/creating.html) to the PlatformIO Registry. You will need to repeat this step on each release.
